const {fs,reportDir,chromium,server,start}=require('./harness.cjs');
const assert=require('assert/strict');
const results=[];
(async()=>{const local=await start(),url=process.env.BASE_URL||local,browser=await chromium.launch({headless:true,channel:'chrome'});try{
async function test(slug,name,fn,options={}){const ctx=await browser.newContext({viewport:{width:1440,height:1050},...options}),page=await ctx.newPage(),errors=[];let accept=true,dialogs=0;page.setDefaultTimeout(7000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',async d=>{dialogs++;await (accept?d.accept():d.dismiss());});try{await page.goto(url+'#'+slug);const r=page.locator('#integram-'+slug),b=name=>r.getByRole('button',{name,exact:true});const result=await fn({page,r,b,ctx,url,setAccept:x=>accept=x,dialogs:()=>dialogs});assert.deepEqual(errors,[]);results.push({slug,name,pass:true,...result});console.log('PASS',slug,name,JSON.stringify(result||{}));}catch(e){results.push({slug,name,pass:false,error:String(e),errors});console.log('FAIL',slug,name,String(e).slice(0,800));await page.screenshot({path:reportDir+'/fix-fail-'+slug+'-'+name+'.png',fullPage:true});}finally{await ctx.close();}}
const stored=async(page,slug,part='data')=>page.evaluate(({slug,part})=>JSON.parse(localStorage.getItem('integram-demo-v3-'+slug+'-sample-'+part)),{slug,part});
const amount=async(page,slug)=>(await stored(page,slug)).tables.find(t=>t.id==='deals').rows.find(r=>r.id===1487).amount;
async function filter(r,b,key,op,value,to){if(!await r.locator('[data-form="filter"]').count())await b('Фильтры').click();const f=r.locator('[data-form="filter"]');await f.locator('[name="key"]').selectOption(key);await f.locator('[name="op"]').selectOption(op);if(op==='in'){for(const v of [].concat(value))await f.locator('input[value="'+v+'"]').check();}else await f.locator('[name="value"]').fill(value);if(to)await f.locator('[name="to"]').fill(to);await b('Добавить условие').click();}
for(const slug of ['contour']){
await test(slug,'R01-number-input',async({page,r,b})=>{
 await r.locator('[data-action="open"][data-id="1487"]').click();
 await b('Сохранить изменения').click(); // initial data may not yet have a storage entry
 for(const value of ['-','1e','+','1e999','abc']){await r.locator('[name="amount"]').fill(value);await b('Сохранить изменения').click();assert.match(await r.locator('.error').innerText(),/Введите число/);assert.equal(await r.locator('[name="amount"]').inputValue(),value);const data=await stored(page,slug);if(data)assert.equal(await amount(page,slug),1240000);await b('История').click();await b('Поля').click();assert.equal(await r.locator('[name="amount"]').inputValue(),value);}
 for(const [value,expected] of [['0',0],['-25.5',-25.5],['12,75',12.75],['1e3',1000],['','']]){await r.locator('[name="amount"]').fill(value);await b('Сохранить изменения').click();assert.equal(await r.locator('.error').count(),0);assert.equal(await amount(page,slug),expected);}
 await b('← К списку').click();await r.locator('[data-action="inline"][data-id="1487"][data-key="amount"]').click();await r.locator('[data-form="inline"] input').fill('-');await b('Сохранить').click();assert.match(await r.locator('.inline-form .error').innerText(),/Введите число/);assert.equal(await r.locator('.inline-form input').inputValue(),'-');assert.equal(await amount(page,slug),'');
});
await test(slug,'R02-inline-draft',async({page,r,b,setAccept,dialogs})=>{
 await r.locator('[data-action="inline"][data-id="1487"][data-key="amount"]').click();await r.locator('.inline-form input').fill('777777');await b('Столбцы').click();assert.equal(await r.locator('.inline-form input').inputValue(),'777777');await r.locator('[data-check="1485"]').check();assert.equal(await r.locator('.inline-form input').inputValue(),'777777');await b('Закрыть настройки').click();
 setAccept(false);await b('Сортировать: Сумма').click();assert.equal(await r.locator('.inline-form input').inputValue(),'777777');await r.locator('[data-search]').fill('Годовая');assert.equal(await r.locator('[data-search]').inputValue(),'');assert.equal(await r.locator('.inline-form input').inputValue(),'777777');await b('Структура').click();assert.equal(await r.locator('.inline-form input').inputValue(),'777777');await page.locator('#preview-data').selectOption('large');assert.equal(await page.locator('#preview-data').inputValue(),'sample');await r.locator('[data-action="table"][data-table="items"]').click();assert.equal(await r.locator('.inline-form input').inputValue(),'777777');assert.equal(await r.locator('[data-check="1487"]').count(),1);assert(dialogs()>=5);
 await b('Сохранить').click();assert.equal(await amount(page,slug),777777);await page.reload();assert.match(await r.locator('[data-row="1487"] td[data-key="amount"]').innerText(),/777\s777/);
});
await test(slug,'R03-R08-board-context-resize',async({page,r,b})=>{
 await page.setViewportSize({width:390,height:844});await b('Доска').click();await r.locator('[name="mobile-stage"]').selectOption('Согласование');assert.equal(await r.locator('.stage:visible .deal').count(),3);assert.match(await r.locator('[data-result-count]').innerText(),/3 из 8/);await r.locator('[data-action="open"][data-id="1487"]').click();await b('Следующая').click();assert.equal(await r.locator('[name="stage"]').inputValue(),'Согласование');assert.match(await r.locator('h2').innerText(),/Расширение/);await b('Следующая').click();assert.equal(await b('Следующая').isDisabled(),true);await b('← К списку').click();
 await b('Ещё').click();const event=page.waitForEvent('download');await b('Экспорт всей выборки в CSV').click();const download=await event;assert.equal(fs.readFileSync(await download.path(),'utf8').split('\r\n').length,4);await page.setViewportSize({width:1440,height:1050});await page.waitForFunction(()=>document.querySelectorAll('.deal').length===8);assert.equal(await r.locator('.deal').count(),8);const counts=await r.locator('.stage').evaluateAll(es=>es.map(e=>[e.querySelectorAll('.deal').length,Number(e.querySelector('h3 span').textContent)]));for(const [cards,count] of counts)assert.equal(cards,count);await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>document.querySelectorAll('.deal').length===3);assert.equal(await r.locator('.deal').count(),3);
});
await test(slug,'R04-empty-stage',async({page,r,b})=>{
 await b('Структура').click();await r.locator('[data-action="field-select"][data-key="stage"]').click();await r.locator('[name="required"]').uncheck();await b('Применить настройки').click();await b('К записям').click();await r.locator('[data-action="open"][data-id="1487"]').click();await r.locator('[name="stage"]').selectOption('');await b('Сохранить изменения').click();await b('← К списку').click();await b('Доска').click();assert.equal(await r.locator('.deal').count(),8);assert.equal(await r.locator('[data-drop-stage=""] [data-drag-record="1487"]').count(),1);await page.setViewportSize({width:390,height:844});await r.locator('[name="mobile-stage"]').selectOption('');assert.equal(await r.locator('.stage:visible .deal').count(),1);await r.locator('[data-drag-record="1487"] summary').click();await r.locator('[name="card-stage"]').selectOption('Новая');assert.equal(await amount(page,slug),1240000);await page.setViewportSize({width:1440,height:1050});await page.waitForFunction(()=>document.querySelectorAll('.deal').length===8);assert.equal(await r.locator('[data-drop-stage="Новая"] [data-drag-record="1487"]').count(),1);
});
await test(slug,'R05-undo-schema-views',async({page,r,b})=>{
 await r.locator('[data-action="inline"][data-id="1487"][data-key="amount"]').click();await r.locator('.inline-form input').fill('1230000');await b('Сохранить').click();await filter(r,b,'owner','in','u0');await b('Закрыть настройки').click();await b('Сохранённые виды: Все записи').click();await r.locator('[data-form="view-save"] input').fill('Мои сделки');await b('Сохранить как новый вид').click();await b('Закрыть настройки').click();const before=await stored(page,slug,'views');await b('Структура').click();await r.locator('[data-action="field-select"][data-key="owner"]').click();await b('Удалить поле').click();await b('Отменить последнее изменение данных').click();assert.equal(await r.locator('tr[data-row]').count(),4);assert.deepEqual(await stored(page,slug,'views'),before);await b('Повторить изменение данных').click();assert.equal(await r.locator('tr[data-row]').count(),8);await b('Отменить последнее изменение данных').click();await b('Отменить последнее изменение данных').click();assert.equal(await amount(page,slug),1240000);await page.reload();assert.equal(await r.locator('tr[data-row]').count(),4);assert.deepEqual(await stored(page,slug,'views'),before);
});
await test(slug,'R06-incompatible-share',async({page,r,b})=>{
 await b('Структура').click();await b('Добавить поле').click();await r.locator('[name="label"]').fill('Приоритет клиента');await b('Создать поле').click();await b('К записям').click();await b('Сохранённые виды: Все записи').click();await b('Ссылка на этот вид').click();assert.equal(await r.locator('[data-focus="share"]').count(),0);assert.match(await r.locator('.settings-panel .error').innerText(),/локальные поля/);
 const payload={version:3,table:'deals',view:{filters:[{key:'custom_field',op:'eq',value:'VIP'}]}};const link=new URL(url);link.searchParams.set('view',JSON.stringify(payload));link.hash=slug;const other=await browser.newContext(),p=await other.newPage();try{await p.goto(link.href);assert.equal(await p.locator('tr[data-row],.deal').count(),0);assert.match(await p.locator('#integram-'+slug+' main').innerText(),/несовместим/);await p.getByRole('button',{name:'Открыть обычное демо',exact:true}).click();assert.equal(await p.locator('tr[data-row],.deal').count(),8);assert(!new URL(p.url()).searchParams.has('view'));}finally{await other.close();}
});
await test(slug,'R07-storage-recovery',async({page,r,b})=>{
 await page.evaluate(()=>{window.originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new DOMException('Quota exceeded','QuotaExceededError');};});await b('Сохранённые виды: Все записи').click();await r.locator('[data-form="view-save"] input').fill('Мой вид');await b('Сохранить как новый вид').click();assert.match(await r.locator('[data-status]').innerText(),/Не удалось сохранить/);assert(!await r.locator('[data-status]').innerText().then(x=>x.includes('сохранён')));assert.equal((await stored(page,slug,'views'))?.deals?.saved?.length||0,0);await b('Закрыть настройки').click();await r.locator('[data-action="open"][data-id="1487"]').click();await r.locator('[name="amount"]').fill('990');await b('Сохранить изменения').click();assert.match(await r.locator('.storage-warning').innerText(),/Не удалось/);await page.evaluate(()=>{Storage.prototype.setItem=window.originalSetItem;});await b('Повторить сохранение').click();assert.equal(await r.locator('.storage-warning').count(),0);assert.equal(await amount(page,slug),990);assert.equal((await stored(page,slug,'views')).deals.saved[0].name,'Мой вид');await page.reload();assert.equal(await amount(page,slug),990);
});
await test(slug,'R09-panel-focus',async({page,r,b})=>{
 for(const [label,key] of [['Сохранённые виды: Все записи','views'],['Фильтры','filters'],['Сортировка','sort'],['Столбцы','columns'],['Группы','group']]){await b(label).click();await b('Закрыть настройки').click();assert.equal(await page.evaluate(()=>document.activeElement.dataset.focus),'tool-'+key);await b(label).click();await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.dataset.focus),'tool-'+key);}
 await page.setViewportSize({width:390,height:844});if(!await b('Столбцы').isVisible())await b('Ещё').click();await b('Столбцы').click();await b('Закрыть настройки').click();assert.equal(await page.evaluate(()=>document.activeElement.dataset.focus),'tool-columns');assert(await b('Столбцы').isVisible());
});
await test(slug,'R10-filter-draft',async({page,r,b})=>{
 await b('Фильтры').click();let f=r.locator('[data-form="filter"]');await f.locator('[name="value"]').fill('Поставка');await f.locator('[name="op"]').selectOption('starts');assert.equal(await f.locator('[name="value"]').inputValue(),'Поставка');await f.locator('[name="op"]').selectOption('empty');await f.locator('[name="op"]').selectOption('contains');assert.equal(await f.locator('[name="value"]').inputValue(),'Поставка');await b('Добавить условие').click();assert.equal(await r.locator('tr[data-row]').count(),1);await b('Сбросить фильтры').click();await f.locator('[name="key"]').selectOption('amount');await f.locator('[name="value"]').fill('500000');await f.locator('[name="op"]').selectOption('between');assert.equal(await f.locator('[name="value"]').inputValue(),'500000');await f.locator('[name="to"]').fill('1000000');await f.locator('[name="op"]').selectOption('gte');await f.locator('[name="op"]').selectOption('between');assert.equal(await f.locator('[name="to"]').inputValue(),'1000000');await b('Добавить условие').click();assert.equal(await r.locator('tr[data-row]').count(),2);
});
await test(slug,'R11-row-density',async({page,r,b})=>{
 await b('Столбцы').click();await r.locator('[data-change="compact"]').uncheck();const regular=await r.locator('tr[data-row]').first().evaluate(e=>e.getBoundingClientRect().height);await r.locator('[data-change="compact"]').check();const compact=await r.locator('tr[data-row]').first().evaluate(e=>e.getBoundingClientRect().height);assert(compact<regular-8,JSON.stringify({regular,compact}));return {regular,compact};
});
await test(slug,'R12-mobile-first-fold',async({page,r,b})=>{
 const metrics=[];for(const width of [320,390]){await page.setViewportSize({width,height:844});for(const screen of ['Таблица','Доска']){await b(screen).click();await page.evaluate(()=>scrollTo(0,0));const target=r.locator(screen==='Доска'?'.deal':'tr[data-row]').first(),box=await target.boundingBox();assert(box.y<620,JSON.stringify({width,screen,y:box.y}));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);metrics.push({width,screen,firstRecordY:Math.round(box.y)});if(width===390)await page.screenshot({path:reportDir+'/'+slug+'-mobile-'+screen+'.png',fullPage:false});}}
 await page.locator('#preview-options').click();assert(await page.locator('#preview-data').isVisible());assert(await page.locator('#preview-theme').isVisible());await b('Меню').click();assert(await b('Все таблицы').isVisible());assert(await b('Сбросить демо').isVisible());await b('Ещё').click();assert(await b('Карточки').isVisible());assert(await b('Сортировка').isVisible());assert(await b('Экспорт всей выборки в CSV').isVisible());return {metrics};
},{isMobile:true,hasTouch:true});
}
}finally{await browser.close();server.close();fs.writeFileSync(reportDir+'/audit-fixes-results.json',JSON.stringify(results,null,2));console.log('RESULT',results.filter(x=>x.pass).length+'/'+results.length);if(results.some(x=>!x.pass))process.exitCode=1;}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
