const {fs,reportDir,chromium,server,start}=require('./harness.cjs');
const assert=require('assert/strict');const results=[];
(async()=>{const local=await start(),base=process.env.BASE_URL||local,browser=await chromium.launch({headless:true,channel:'chrome'});
try{
async function test(slug,name,fn){const ctx=await browser.newContext({viewport:{width:1440,height:1000},bypassCSP:true}),page=await ctx.newPage(),errors=[],dialogs=[];page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>{dialogs.push(d.message());d.accept();});try{const url=new URL(base);url.searchParams.set('data','stress');url.hash=slug;await page.goto(url.href);const r=page.locator('#integram-'+slug),b=name=>r.getByRole('button',{name,exact:true});await r.locator('main').waitFor();if(await r.locator('[data-action="screen"][data-screen="table"]').count())await b('Таблица').click();await fn({page,r,b,dialogs,url});assert.deepEqual(errors,[]);results.push({slug,name,pass:true});console.log('PASS',slug,name);}catch(e){results.push({slug,name,pass:false,error:String(e),errors});console.log('FAIL',slug,name,String(e).slice(0,1600));await page.screenshot({path:reportDir+'/dictionary-fail-'+slug+'-'+name+'.png',fullPage:false});}finally{await ctx.close();}}
const source=(r,table,key)=>r.locator('[data-action="dictionary-open"][data-table="'+table+'"]'+(key?'[data-key="'+key+'"]':'[data-kind="reference"]'));
for(const slug of ['contour']){
await test(slug,'catalog-and-usage',async({page,r,b,url})=>{
 await b('Справочники').click();assert.equal(await r.locator('h2').innerText(),'Справочники');const expected=await page.evaluate(()=>{const d=IntegramStressSeed.baseline(),refs=new Set();let choices=0;for(const t of d.tables)for(const f of t.fields){if(f.type==='reference')refs.add(f.ref);if(f.type==='choice')choices++;}return refs.size+choices;});assert.equal(await r.locator('.dictionary-source').count(),expected);
 await r.locator('[data-dictionary-search]').fill('Кредит');assert.equal(await r.locator('.dictionary-source').count(),0);await r.locator('[data-dictionary-search]').fill('Ответственный');assert(await source(r,'people').count());await r.locator('[data-dictionary-search]').fill('');
 await source(r,'companies').click();assert.match(await r.locator('[data-result-count]').innerText(),/1200 из 1200/);assert.equal(await r.locator('.rail [aria-current="page"]').count(),1);await r.locator('.dictionary-uses summary').click();assert((await r.locator('.dictionary-uses li').count())>2);await r.locator('[data-action="dictionary-back"]').click();
 await source(r,'deals','stage').click();assert.equal(await r.locator('[data-dictionary-value]').count(),8);const value='В работе',expectedUsed=await page.evaluate(value=>IntegramStressSeed.baseline().tables[0].rows.filter(r=>r.stage===value).length,value);await b('Записи со значением: '+value).click();assert.match(await r.locator('[data-result-count]').innerText(),new RegExp(expectedUsed+' из 12000'));assert.match(await r.locator('.filter-chip').innerText(),/Этап.*В работе/);await r.locator('[data-action="dictionary-back"]').click();assert.equal(await r.locator('[data-dictionary-value]').count(),8);
 await b('Записи без значения: Этап').click();assert.match(await r.locator('[data-result-count]').innerText(),/325 из 12000/);await r.locator('[data-action="dictionary-back"]').click();await r.locator('[data-action="dictionary-back"]').click();
 url.searchParams.set('section','dictionaries');await page.goto(url.href);assert.equal(await r.locator('h2').innerText(),'Справочники');assert.equal(await r.locator('.dictionary-source').count(),expected);
});
await test(slug,'draft-and-reference-roundtrip',async({page,r,b,dialogs})=>{
 await r.locator('[data-action="table"][data-table="companies"]').click();await b('Фильтры').click();await r.locator('[data-form="filter"] [name="key"]').selectOption('kind');await r.locator('[data-form="filter"] input[value="Перевозчик"]').check();await b('Добавить условие').click();await r.locator('[data-action="table"][data-table="deals"]').click();
 await r.locator('[data-action="open"]').first().click();const draft='Несохранённый комментарий при просмотре справочника';await r.locator('[name="note"]').fill(draft);await r.locator('[name="company"]').selectOption('c1');await b('Открыть справочник поля: Заказчик').click();assert.match(await r.locator('[data-result-count]').innerText(),/1200 из 1200/);await b('Добавить запись').click();await r.locator('[name="name"]').fill('Новый контрагент из справочника');await b('Создать запись').click();const id=await r.locator('.record-title .pill').innerText();assert.match(id,/^#r/);await r.locator('[data-action="dictionary-back"]').click();assert.equal(await r.locator('[name="note"]').inputValue(),draft);assert.equal(await r.locator('[name="company"]').inputValue(),'c1');assert.equal(await r.locator('[name="company"] option').filter({hasText:'Новый контрагент из справочника'}).count(),1);assert.deepEqual(dialogs,[]);
 await r.locator('[name="company"]').selectOption(id.slice(1));await b('Сохранить изменения').click();await page.reload();await r.locator('[data-action="screen"][data-screen="table"]').click();await r.locator('[data-action="open"]').first().click();assert.equal(await r.locator('[name="note"]').inputValue(),draft);assert.equal(await r.locator('[name="company"]').inputValue(),id.slice(1));await r.locator('[data-action="table"][data-table="companies"]').click();assert.match(await r.locator('[data-result-count]').innerText(),/300 из 1201/);
});
await test(slug,'choice-edit-filter-inline',async({page,r,b,dialogs})=>{
 await b('Фильтры').click();await r.locator('[data-form="filter"] [name="key"]').selectOption('company');await r.locator('[data-form="filter"] input[value="c0"]').check();await b('Открыть справочник поля: Заказчик').click();await r.locator('[data-action="dictionary-back"]').click();assert.equal(await r.locator('[data-form="filter"] input[value="c0"]').isChecked(),true);await b('Закрыть настройки').click();
 await r.locator('[data-action="inline"][data-id="700001"][data-key="stage"]').click();await r.locator('[data-form="inline"] [name="stage"]').selectOption('В работе');await b('Открыть справочник поля: Этап').click();assert.equal(await r.locator('[data-dictionary-value]').count(),8);await r.locator('[data-action="dictionary-back"]').click();assert.equal(await r.locator('[data-form="inline"] [name="stage"]').inputValue(),'В работе');await b('Сохранить').click();
 await b('Справочники').click();await source(r,'deals','stage').click();await b('Настроить список').click();const options=r.locator('[data-form="schema"] [name="options"]'),previous=await options.inputValue(),extra=Array.from({length:107},(_,i)=>'Проверка '+String(i).padStart(3,'0'));extra[0]='<Согласование & контроль>';await options.fill(previous+'\n'+extra.join('\n'));await b('Применить настройки').click();await r.locator('[data-action="dictionary-back"]').click();assert.match(await r.locator('[data-dictionary-count]').innerText(),/115 из 115/);assert.equal(await r.locator('[data-dictionary-value]').count(),50);await b('Следующая страница справочника').click();assert.equal(await r.locator('[data-dictionary-value]').count(),50);await r.locator('[data-dictionary-value-search]').fill('Проверка 106');assert.equal(await r.locator('[data-dictionary-value]').count(),1);await r.locator('[data-dictionary-value-search]').fill('<Согласование');assert.equal(await r.locator('[data-dictionary-value]').count(),1);assert.equal(await page.locator('согласование').count(),0);await r.locator('[data-dictionary-value-search]').fill('');await r.locator('[name="dictionary-sort"]').selectOption('desc');assert.match(await r.locator('[data-dictionary-value]').first().innerText(),/Согласование договора/);
 await r.locator('[data-action="table"][data-table="deals"]').click();await r.locator('[data-action="open"]').first().click();assert.equal(await r.locator('[name="stage"] option').count(),116);await r.locator('[name="stage"]').selectOption(extra[0]);await b('Сохранить изменения').click();await page.reload();await r.locator('[data-action="screen"][data-screen="table"]').click();await r.locator('[data-action="open"]').first().click();assert.equal(await r.locator('[name="stage"]').inputValue(),extra[0]);assert.deepEqual(dialogs,[]);
});
await test(slug,'hidden-draft-navigation-guard',async({page,r,b})=>{
 await r.locator('[data-action="open"]').first().click();await r.locator('[name="note"]').fill('Этот черновик должен пережить просмотр справочника');await b('Открыть справочник поля: Заказчик').click();page.removeAllListeners('dialog');let prompt='';page.on('dialog',d=>{prompt=d.message();d.dismiss();});await r.locator('[data-action="table"][data-table="items"]').click();assert.match(prompt,/исходной форме/);assert.match(await r.locator('h2').innerText(),/Контрагенты/);assert.equal(await r.locator('[data-action="dictionary-back"]').count(),1);await page.locator('#preview-data').selectOption('sample');assert.equal(await page.locator('#preview-data').inputValue(),'stress');prompt='';await b('Все таблицы').click();assert.match(prompt,/исходной форме/);assert.match(await r.locator('h2').innerText(),/Контрагенты/);assert.equal(await r.locator('[data-action="dictionary-back"]').count(),1);await r.locator('[data-action="dictionary-back"]').click();assert.equal(await r.locator('[name="note"]').inputValue(),'Этот черновик должен пережить просмотр справочника');
});
await test(slug,'themes-mobile-and-keyboard',async({page,r,b})=>{
 await b('Справочники').click();await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});let checks=0;
 for(const theme of ['light','dark']) {await page.locator('#preview-theme').selectOption(theme);for(const screen of ['catalog','choice','reference']) {if(screen==='choice')await source(r,'deals','stage').click();if(screen==='reference')await source(r,'companies').click();for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,screen+':'+width);checks++;}
 const violations=await page.evaluate(async()=> (await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','best-practice']}})).violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)})));assert.deepEqual(violations,[]);if(theme==='light')await page.screenshot({path:reportDir+'/dictionary-'+slug+'-'+screen+'.png',fullPage:false});await page.setViewportSize({width:390,height:844});const mobile=await page.evaluate(async()=> (await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}})).violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)})));assert.deepEqual(mobile,[]);if(theme==='light'){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:reportDir+'/dictionary-'+slug+'-'+screen+'-mobile.png',fullPage:false});}await page.setViewportSize({width:1440,height:1000});if(screen!=='catalog')await r.locator('[data-action="dictionary-back"]').click();}}
 assert.equal(checks,24);await source(r,'deals','priority').focus();await page.keyboard.press('Enter');assert.equal(await r.locator('h2').innerText(),'Приоритет');await r.locator('[data-action="dictionary-back"]').click();await page.setViewportSize({width:320,height:844});await r.locator('[name="table-mobile"]').selectOption('items');assert.match(await r.locator('[data-result-count]').innerText(),/50000 из 50000/);await r.locator('[name="table-mobile"]').selectOption('__dictionaries__');assert.equal(await r.locator('h2').innerText(),'Справочники');
});
}
}finally{await browser.close();server.close();fs.writeFileSync(reportDir+'/dictionary-results.json',JSON.stringify(results,null,2));console.log('RESULT',results.filter(x=>x.pass).length+'/'+results.length);if(results.some(x=>!x.pass))process.exitCode=1;}
})().catch(e=>{console.error(e);server.close();process.exitCode=1});
