const {fs,reportDir,chromium,server,start}=require('./harness.cjs');
const assert=require('node:assert/strict');
const results=[];
(async()=>{const local=await start(),base=process.env.BASE_URL||local,browser=await chromium.launch({headless:true,channel:'chrome'});
try{
async function test(slug,name,fn){const ctx=await browser.newContext({viewport:{width:1440,height:1000}}),page=await ctx.newPage(),errors=[],dialogs=[];page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>{dialogs.push(d.message());d.accept();});try{const url=new URL(base);url.searchParams.set('data','stress');url.hash=slug;await page.goto(url.href);const r=page.locator('#integram-'+slug),b=name=>r.getByRole('button',{name,exact:true});await r.locator('main').waitFor();const openTable=async id=>{const mobile=r.locator('[data-change="table-mobile"]');if(await mobile.isVisible())await mobile.selectOption(id);else await r.locator('[data-action="table"][data-table="'+id+'"]').click();};const tree=async id=>{await openTable(id);await r.locator('[data-action="screen"][data-screen="hierarchy"]').click();await r.locator('.hierarchy-toolbar').waitFor();};await fn({page,r,b,ctx,tree,openTable,url,dialogs});assert.deepEqual(errors,[]);results.push({slug,name,pass:true});console.log('PASS',slug,name);}catch(error){results.push({slug,name,pass:false,error:String(error),errors});console.log('FAIL',slug,name,String(error).slice(0,1800));await page.screenshot({path:reportDir+'/hierarchy-fail-'+slug+'-'+name+'.png',fullPage:false});}finally{await ctx.close();}}
const toggle=(r,id)=>r.locator('[data-action="h-toggle"][data-id="'+id+'"]');
const nodes=r=>r.locator('[data-h-node]');
for(const slug of ['contour','register','focus']){
 await test(slug,'tree-keyboard-views-reload',async({page,r,b,tree,openTable})=>{
  await tree('tasks');assert.match(await r.locator('[data-result-count]').innerText(),/6000 из 6000/);assert.equal(await nodes(r).count(),25);const first=await nodes(r).first().getAttribute('data-h-node');assert.equal(first,'task000001');await toggle(r,first).focus();await page.keyboard.press('Enter');assert.equal(await toggle(r,first).getAttribute('aria-expanded'),'true');assert.equal(await nodes(r).count(),36);
  await r.locator('[data-action="panel"][data-panel="views"]').click();await r.locator('[data-form="view-save"] [name="name"]').fill('Задачи с раскрытой веткой');await b('Сохранить как новый вид').click();await b('Закрыть настройки').click();await toggle(r,first).click();assert.equal(await nodes(r).count(),25);await r.locator('[data-change="quick-view"]').selectOption({label:'Задачи с раскрытой веткой'});assert.equal(await nodes(r).count(),36);
  await page.reload();await openTable('tasks');assert.equal(await r.locator('[data-screen="hierarchy"]').getAttribute('aria-pressed'),'true');assert.equal(await toggle(r,first).getAttribute('aria-expanded'),'true');assert.equal(await nodes(r).count(),36);await toggle(r,first).click();await page.reload();await openTable('tasks');assert.equal(await toggle(r,first).getAttribute('aria-expanded'),'false');assert.equal(await nodes(r).count(),25);
  await r.locator('[data-action="panel"][data-panel="hierarchy"]').first().click();await r.locator('[data-change="h-parent"]').selectOption('');assert.match(await r.locator('.hierarchy-toolbar strong').innerText(),/Связанные таблицы/);await b('Закрыть настройки').click();await r.locator('[data-change="quick-view"]').selectOption({label:'Задачи с раскрытой веткой'});assert.match(await r.locator('.hierarchy-toolbar strong').innerText(),/Дерево записей/);assert.equal(await nodes(r).count(),36);
 });
 await test(slug,'filter-ancestor-context-and-search',async({page,r,b,tree})=>{
  await tree('tasks');await r.locator('[data-action="panel"][data-panel="filters"]').click();await r.locator('[data-form="filter"] [name="key"]').selectOption('external');await r.locator('[data-form="filter"] [name="op"]').selectOption('eq');await r.locator('[data-form="filter"] [name="value"]').fill('REQ-00000001');await b('Добавить условие').click();await b('Закрыть настройки').click();assert.match(await r.locator('[data-result-count]').innerText(),/1 из 6000/);assert.equal(await nodes(r).count(),2);assert.equal(await r.locator('.hierarchy-context').count(),1);assert.match(await r.locator('.hierarchy-toolbar').innerText(),/1 родительских записей для контекста, вне подсчёта/);
  await r.locator('[data-h-node="task000001"] [data-action="h-open"]').click();assert.match(await r.locator('.record-title .pill').innerText(),/task000001/);assert.match(await r.locator('.record-header').innerText(),/1 из 1/);await r.locator('[data-action="reference-back"]').click();assert.equal(await r.locator('[data-screen="hierarchy"]').getAttribute('aria-pressed'),'true');assert.equal(await nodes(r).count(),2);assert.match(await r.locator('[data-result-count]').innerText(),/1 из 6000/);
  await toggle(r,'task000001').click();assert.equal(await nodes(r).count(),1);await toggle(r,'task000001').click();assert.equal(await nodes(r).count(),2);await r.locator('[data-action="filter-remove"]').click();await r.locator('[data-search]').fill('task000014');await page.waitForTimeout(250);assert.match(await r.locator('[data-result-count]').innerText(),/1 из 6000/);assert.equal(await nodes(r).count(),2);assert.equal(await nodes(r).first().getAttribute('data-h-node'),'task000013');assert.match(await r.locator('.hierarchy-context').innerText(),/вне выборки/);
 });
 await test(slug,'related-full-list-edit-and-return',async({page,r,b,tree,dialogs})=>{
  await tree('deals');const first=await nodes(r).first().getAttribute('data-h-node'),related=r.locator('[data-h-node="'+first+'"] [data-action="h-related-toggle"]').first();await related.focus();await page.keyboard.press('Enter');assert.equal(await related.getAttribute('aria-expanded'),'true');const section=r.locator('.hierarchy-related').first(),childId=await section.locator('[data-h-related-row]').first().getAttribute('data-h-related-row');assert.match(await section.locator('thead').innerText(),/Количество/);assert.equal(await section.locator('[data-h-related-row]').count(),5);await section.locator('[data-action="related-list"]').click();assert.match(await r.locator('h2').innerText(),/Позиции поставок/);assert.match(await r.locator('[data-result-count]').innerText(),/5 из 50000/);await r.locator('[data-action="open"][data-id="'+childId+'"]').click();await r.locator('[data-form="record"] [name="qty"]').fill('123.75');await b('Сохранить изменения').click();await r.locator('[data-action="reference-back"]').click();assert.equal(await r.locator('[data-screen="hierarchy"]').getAttribute('aria-pressed'),'true');assert.equal(await r.locator('[data-h-node="'+first+'"] [data-action="h-related-toggle"]').first().getAttribute('aria-expanded'),'true');assert.match(await r.locator('[data-h-related-row="'+childId+'"]').innerText(),/123,75/);assert.match(await r.locator('[data-result-count]').innerText(),/12000 из 12000/);
  await r.locator('[data-h-related-row="'+childId+'"] [data-action="reference"]').click();assert.equal(await r.locator('[data-form="record"] [name="qty"]').inputValue(),'123.75');await r.locator('[data-action="reference-back"]').click();assert.equal(await r.locator('[data-screen="hierarchy"]').getAttribute('aria-pressed'),'true');assert.deepEqual(dialogs,[]);
 });
 await test(slug,'mobile-tree-relations-and-layout',async({page,r,b,tree,openTable})=>{
  await page.setViewportSize({width:390,height:844});await tree('tasks');const first='task000001';await toggle(r,first).focus();await page.keyboard.press('Enter');assert.equal(await nodes(r).count(),36);const layout=await page.evaluate(()=>{const first=document.querySelector('[data-h-node]'),next=first.nextElementSibling,a=first.getBoundingClientRect(),b=next.getBoundingClientRect();return {overlap:a.bottom>b.top+.5,overflow:document.documentElement.scrollWidth>innerWidth+1}});assert.deepEqual(layout,{overlap:false,overflow:false});
  await tree('deals');await r.locator('[data-action="h-related-toggle"]').first().click();const sizes=await r.evaluate(el=>{const parent=el.querySelector('[data-h-node]'),related=el.querySelector('.hierarchy-details'),wrap=el.querySelector('.hierarchy-related-wrap');return {overlap:parent.getBoundingClientRect().bottom>related.getBoundingClientRect().top+.5,overflow:document.documentElement.scrollWidth>innerWidth+1,localScroll:wrap.scrollWidth>wrap.clientWidth}});assert.deepEqual(sizes,{overlap:false,overflow:false,localScroll:true});await r.locator('.hierarchy-related [data-action="related-list"]').first().click();assert.match(await r.locator('h2').innerText(),/Позиции поставок/);await r.locator('[data-action="reference-back"]').click();assert.equal(await r.locator('[data-screen="hierarchy"]').getAttribute('aria-pressed'),'true');
  await page.setViewportSize({width:320,height:768});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:reportDir+'/hierarchy-mobile-'+slug+'.png',fullPage:false});
 });
}
}finally{await browser.close();server.close();fs.writeFileSync(reportDir+'/hierarchy-browser-results.json',JSON.stringify(results,null,2));}
console.log(JSON.stringify({passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass).length},null,2));if(results.some(r=>!r.pass))process.exitCode=1;
})().catch(error=>{console.error(error);server.close();process.exitCode=1});
