const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const context=vm.createContext({console,structuredClone,Intl,Map,Set,WeakMap,window:{}});
for(const name of ['model','ui','hierarchy']){vm.runInContext(fs.readFileSync(path.resolve(__dirname,'../../redesign/assets/'+name+'.js'),'utf8'),context,{filename:name+'.js'});Object.assign(context,context.window);}
const H=context.IntegramHierarchy,M=context.IntegramModel;
const checks=[];
function test(name,fn){fn();checks.push(name);console.log('PASS',name);}
const field=(key,label,type='text',extra={})=>({key,label,type,...extra});
const table=(rows)=>({id:'tasks',name:'Задачи',fields:[field('name','Задача','text',{primary:true}),field('parent','Родитель','reference',{ref:'tasks'}),field('amount','Стоимость','number')],rows});
const settings=(t)=>H.defaults({tables:[t]},t);
function app(data,t,rows=t.rows){const v=M.defaults(t,'contour');v.hierarchy=H.defaults(data,t);return {data,t,rows,v,id:'contour',s:{search:'',checked:new Set()},persistView(){this.persisted=true;},render(){this.rendered=true;},openRecord(id){this.opened=id;},reference(...args){this.referenced=args;}};}

test('filtered matches preserve ancestors without counting them',()=>{const t=table([{id:'a',name:'Родитель'},{id:'b',name:'Ветка',parent:'a'},{id:'c',name:'Совпадение',parent:'b'},{id:'d',name:'Скрытый сосед',parent:'a'}]),tree=H.buildTree(t,[t.rows[2]],'parent');assert.equal(tree.matchedCount,1);assert.equal(tree.contextCount,2);assert.equal(tree.roots.length,1);assert.equal(tree.roots[0].matchCount,1);assert.equal(tree.roots[0].totalCount,4);assert.deepEqual(Array.from(tree.roots[0].visibleChildren,n=>n.id),['b']);const flat=H.flatten(tree,settings(t),{autoContext:true});assert.deepEqual(Array.from(flat.entries.filter(x=>x.kind==='node'),x=>x.node.id),['a','b','c']);});

test('cycles and missing parents remain reachable exactly once',()=>{const t=table([{id:'a',name:'A',parent:'b'},{id:'b',name:'B',parent:'a'},{id:'c',name:'C',parent:'c'},{id:'d',name:'D',parent:'missing'},{id:'e',name:'E',parent:'b'}]),before=JSON.stringify(t),tree=H.buildTree(t,t.rows,'parent'),c=settings(t);c.expanded=t.rows.map(r=>r.id);const flat=H.flatten(tree,c),ids=Array.from(flat.entries.filter(x=>x.kind==='node'),x=>x.node.id);assert.equal(tree.issues.cycles,2);assert.equal(tree.issues.missingParents,1);assert.equal(new Set(ids).size,5);assert.equal(ids.length,5);assert.equal(tree.roots.reduce((sum,n)=>sum+n.matchCount,0),5);assert.equal(JSON.stringify(t),before);});

test('50,000-level parent chain is iterative and rendering is bounded',()=>{const t=table(Array.from({length:50000},(_,i)=>({id:String(i),name:'Узел '+i,parent:i?String(i-1):''}))),tree=H.buildTree(t,[t.rows[49999]],'parent'),flat=H.flatten(tree,settings(t),{autoContext:true});assert.equal(tree.contextCount,49999);assert.equal(tree.roots[0].totalCount,50000);assert.equal(flat.nodeCount,H.limits.MAX_NODES);assert.equal(flat.next,'160');assert.equal(tree.roots[0].matchCount,1);});

test('branch paging is independent from root paging and retains order',()=>{const t=table([{id:'root',name:'Root'},...Array.from({length:501},(_,i)=>({id:'c'+i,name:'Child '+i,parent:'root'}))]),sorted=[t.rows[0],...t.rows.slice(1).reverse()],tree=H.buildTree(t,sorted,'parent'),c=settings(t);c.expanded=['root'];c.branchPages.root=2;const flat=H.flatten(tree,c),ids=Array.from(flat.entries.filter(x=>x.kind==='node'),x=>x.node.id);assert.equal(ids.length,26);assert.equal(ids[1],'c475');assert.equal(ids.at(-1),'c451');assert.equal(flat.entries.at(-1).pages,21);});

test('50,000 roots only render one page',()=>{const t=table(Array.from({length:50000},(_,i)=>({id:String(i),name:'Запись '+i}))),tree=H.buildTree(t,t.rows,''),c=settings(t);c.page=2000;const flat=H.flatten(tree,c);assert.equal(flat.nodeCount,25);assert.equal(flat.pages,2000);assert.equal(flat.entries[0].node.id,'49975');});

test('normalization removes stale parent fields and deleted relations',()=>{const t=table([{id:'a',name:'A'}]),data={tables:[t]},c=H.normalize(data,t,{parentKey:'gone',relations:['items::deal'],expanded:['a','gone'],page:-5,focusId:'gone',relationOpen:['bad']} );assert.equal(c.parentKey,'parent');assert.equal(c.relations.length,0);assert.deepEqual(Array.from(c.expanded),['a']);assert.equal(c.page,1);assert.equal(c.focusId,'');assert.equal(c.relationOpen.length,0);t.fields=t.fields.filter(f=>f.key!=='parent');assert.equal(H.normalize(data,t,c).parentKey,'');});

test('separate entities retain own headers and full reference counts',()=>{const t=table([{id:'a',name:'Договор',amount:100000}]),other={id:'items',name:'Позиции',fields:[field('name','Наименование позиции','text',{primary:true}),field('deal','Договор','reference',{ref:'tasks'}),field('qty','Количество','number')],rows:Array.from({length:57},(_,i)=>({id:'i'+i,name:'Позиция '+i,deal:'a',qty:i+1}))},data={tables:[t,other]},a=app(data,t);a.v.hierarchy.relationOpen=[JSON.stringify(['a','items::deal'])];const index=H.relatedIndex(data,t,a.v.hierarchy);assert.equal(index[0].byParent.get('a').length,57);const html=H.render(a);assert.match(html,/Наименование позиции/);assert.match(html,/Количество/);assert.match(html,/57 связанных записей/);assert.equal((html.match(/data-h-related-row=/g)||[]).length,10);assert.match(html,/data-action="related-list" data-table="items" data-key="deal" data-value="a"/);assert.doesNotMatch(html,/Итого:/);});

test('HTML escapes names, ids, values and related-table headings',()=>{const t=table([{id:'x"<',name:'<img src=x onerror=alert(1)>',amount:10}]),a=app({tables:[t]},t),html=H.render(a);assert(!html.includes('<img'));assert(html.includes('&lt;img'));assert(html.includes('x&quot;&lt;'));});

test('explicitly collapsed context remains collapsed during search',()=>{const t=table([{id:'a',name:'A'},{id:'b',name:'B',parent:'a'}]),a=app({tables:[t]},t,[t.rows[1]]);a.s.search='B';H.render(a);assert(a.hierarchyExpanded.has('a'));H.handleAction(a,'h-toggle',{id:'a'});const html=H.render(a);assert(!a.hierarchyExpanded.has('a'));assert.equal((html.match(/data-h-node=/g)||[]).length,1);H.handleAction(a,'h-toggle',{id:'a'});assert.equal((H.render(a).match(/data-h-node=/g)||[]).length,2);});

test('open unmatched context goes through reference navigation',()=>{const t=table([{id:'a',name:'A'},{id:'b',name:'B',parent:'a'}]),a=app({tables:[t]},t,[t.rows[1]]);H.handleAction(a,'h-open',{id:'a'});assert.deepEqual(a.referenced,['tasks','a','a']);H.handleAction(a,'h-open',{id:'b'});assert.equal(a.opened,'b');assert.equal(H.handleAction(a,'other',{}),false);});

test('related records have a shared render budget across independent branches',()=>{const t=table(Array.from({length:25},(_,i)=>({id:'a'+i,name:'A'+i}))),other={id:'items',name:'Позиции',fields:[field('name','Позиция','text',{primary:true}),field('deal','Договор','reference',{ref:'tasks'})],rows:Array.from({length:50000},(_,i)=>({id:'i'+i,name:'I'+i,deal:'a'+i%25}))},data={tables:[t,other]},a=app(data,t);a.v.hierarchy.relationOpen=t.rows.map(r=>JSON.stringify([r.id,'items::deal']));const html=H.render(a);assert.equal((html.match(/data-h-node=/g)||[]).length,25);assert.equal((html.match(/data-h-related-row=/g)||[]).length,H.limits.MAX_RELATED);assert.match(html,/2[\s\u00a0]000 связанных записей/);});

test('opening a deep branch and returning home change only view state',()=>{const t=table([{id:'a',name:'A'},{id:'b',name:'B',parent:'a'},{id:'c',name:'C',parent:'b'}]),a=app({tables:[t]},t),before=JSON.stringify(a.data);H.handleAction(a,'h-focus',{id:'b'});assert.equal(a.v.hierarchy.focusId,'b');assert.match(H.render(a),/Путь к ветке/);H.handleAction(a,'h-home',{});assert.equal(a.v.hierarchy.focusId,'');assert.equal(JSON.stringify(a.data),before);assert(a.persisted);});
console.log(JSON.stringify({passed:checks.length,checks},null,2));
