const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'../../redesign/assets'),context={Intl,Date,Map,Set,WeakMap,Number,String,Array,Object,Math,JSON,structuredClone,console};context.window=context;vm.createContext(context);for(const file of ['model.js','grouping.js','pivot.js','stress-seed.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context,{filename:file});
const P=context.IntegramPivot,G=context.IntegramGrouping;let passed=0;
function test(name,fn){fn();passed++;console.log('PASS',name);}
const t={id:'payments',name:'Платежи',fields:[{key:'name',label:'Название',type:'text',primary:true},{key:'company',label:'Контрагент',type:'reference',ref:'companies'},{key:'stage',label:'Статус',type:'choice',options:['Б','А']},{key:'date',label:'Дата',type:'date'},{key:'amount',label:'Сумма',type:'number',currency:true},{key:'original',label:'В валюте',type:'number'},{key:'currency',label:'Валюта',type:'choice',options:['RUB','USD']},{key:'tags',label:'Метки',type:'text'},{key:'qty',label:'Количество',type:'number'},{key:'unit',label:'Единица',type:'text'}],rows:[{id:'1',name:'Первый',company:'a',stage:'А',date:'2025-01-02',amount:100,original:100,currency:'RUB',tags:'x;y',qty:2,unit:'шт.'},{id:'2',name:'Второй',company:'b',stage:'А',date:'2025-02-03',amount:300,original:3,currency:'USD',tags:'x',qty:3,unit:'кг'},{id:'3',name:'Третий',company:'a',stage:'Б',date:'2026-01-02',amount:1000,original:1000,currency:'RUB',tags:'y',qty:5,unit:'шт.'},{id:'4',name:'<img src=x>',company:'a',stage:'Б',date:'2026-02-03',amount:'',original:'',currency:'',tags:'',qty:0,unit:'шт.'}]},companies={id:'companies',name:'Контрагенты',fields:[{key:'name',label:'Название',type:'text',primary:true},{key:'budget',label:'Бюджет',type:'number'}],rows:[{id:'a',name:'Одинаковое имя',budget:100},{id:'b',name:'Одинаковое имя',budget:200}]},data={tables:[t,companies]};
const rules=(...keys)=>keys.map(key=>({key,mode:'value'})),measures=[{id:'count',op:'count'},{id:'sum',key:'amount',op:'sum'},{id:'avg',key:'amount',op:'avg'},{id:'unique',key:'company',op:'distinct'}];
function cfg(extra={}){return {rows:rules('company','stage'),columns:[{key:'date',mode:'year'},{key:'date',mode:'month'}],measures,rowDepth:2,columnDepth:2,maxColumns:60,...extra};}
function app(config=cfg(),rows=t.rows){return {data,t,rows,v:{pivot:config,pageSize:25},s:{page:1},persistView(){this.saved=true;},viewChanged(){this.s.page=1;this.changed=true;},render(){this.rendered=true;}};}
test('normalization rejects missing fields and linked-number double counting',()=>{const n=P.normalize(data,t,cfg({rows:rules('missing','stage'),measures:[{id:'unsafe',op:'sum',key:'company.budget'},{id:'sum',op:'sum',key:'amount'}]}));assert.equal(n.rows.length,1);assert.equal(n.measures.length,1);assert.equal(n.measures[0].key,'amount');});
test('same reference labels do not merge identities',()=>{const m=P.build(data,t,t.rows,cfg());assert.equal(m.rowRoot.children.length,2);assert.notEqual(m.rowRoot.children[0].path,m.rowRoot.children[1].path);assert.match(m.rowRoot.children[0].label,/#a/);});
test('full totals count records once and average underlying numeric values',()=>{const m=P.build(data,t,t.rows,cfg()),total=m.getCell();assert.equal(total.count,4);assert.equal(total.summaries[1].value,1400);assert.equal(total.summaries[2].value,1400/3);assert.equal(total.summaries[3].value,2);});
test('nested row and column intersection drills only its matching IDs',()=>{const m=P.build(data,t,t.rows,cfg()),rn=m.rowRoot.children.find(n=>n.label.endsWith('#a')).children.find(n=>n.label==='Б'),cn=m.columnRoot.children.find(n=>n.label==='2026').children.find(n=>n.label.includes('январ'));assert.deepEqual([...m.getCell(rn.path,cn.path).ids],['3']);assert.equal(m.getCell(rn.path,cn.path).summaries[1].value,1000);});
test('filter precedes all aggregates',()=>{const m=P.build(data,t,t.rows.filter(r=>r.id!=='3'),cfg());assert.equal(m.getCell().summaries[1].value,400);assert.equal(m.getCell().count,3);});
test('expanded column branches include intermediate totals',()=>{const m=P.build(data,t,t.rows,cfg()),cols=P.visibleColumns(m);assert.equal(cols.length,6);assert.equal(cols.filter(n=>n.subtotal).length,2);assert.equal(m.getCell('[]',cols.find(n=>n.subtotal&&n.label.includes('2025')).path).summaries[1].value,400);});
test('column collapse preserves aggregate across descendant months',()=>{const m=P.build(data,t,t.rows,cfg()),path=m.columnRoot.children[0].path,c=cfg({columnCollapsed:[path]}),collapsed=P.build(data,t,t.rows,c);assert.equal(P.visibleColumns(collapsed).length,4);assert.equal(collapsed.getCell('[]',path).summaries[1].value,400);});
test('row collapse hides only descendants and retains group totals',()=>{const m=P.build(data,t,t.rows,cfg()),path=m.rowRoot.children[0].path,c=cfg({rowCollapsed:[path]}),collapsed=P.build(data,t,t.rows,c);assert(P.visibleRows(collapsed).length<P.visibleRows(m).length);assert.equal(collapsed.getCell(path,'[]').count,3);});
test('mixed currencies and quantities remain separated',()=>{const m=P.build(data,t,t.rows,cfg({measures:[{id:'original',key:'original',op:'sum'},{id:'qty',key:'qty',op:'sum'}]})),s=m.getCell().summaries;assert.equal(s[0].value,null);assert.equal(s[0].parts.length,2);assert.equal(s[1].value,null);assert.equal(s[1].parts.find(p=>p.unit==='шт.').value,7);});
test('exploded tags do not duplicate the overall total',()=>{const m=P.build(data,t,t.rows,cfg({rows:[{key:'tags',mode:'tags'}],columns:[],measures:[{id:'sum',key:'amount',op:'sum'}]}));assert.equal(m.getCell().summaries[0].value,1400);assert.equal(m.rowRoot.children.find(n=>n.label==='x').rows.length,2);assert.equal(m.rowRoot.children.find(n=>n.label==='y').rows.length,2);});
test('year and quarter differ from repeated raw date dimensions',()=>{const n=P.normalize(data,t,cfg({columns:[{key:'date',mode:'year'},{key:'date',mode:'quarter'},{key:'date',mode:'month'}]}));assert.equal(n.columns.length,3);assert.equal(P.build(data,t,t.rows,n).columnRoot.children.length,2);});
test('range buckets distinguish negatives and zero',()=>{const rows=[{id:'n',qty:-1},{id:'z',qty:0},{id:'p',qty:10}],m=P.build(data,t,rows,cfg({rows:[{key:'qty',mode:'range',size:10}],columns:[]}));assert.equal(m.rowRoot.children.length,3);assert(m.rowRoot.children[0].label.startsWith('−')||m.rowRoot.children[0].label.startsWith('-'));});
test('render generates safe labels and complete drill maps',()=>{const a=app(cfg({rows:rules('name'),columns:[]})),html=P.render(a);assert(!html.includes('<img src=x>'));assert(html.includes('&lt;img src=x&gt;'));assert.equal(a.s.pivotCells.size,5);assert.equal([...a.s.pivotCells.values()].find(x=>x.length===4).length,4);});
test('zero records produce an honest empty state',()=>{const a=app(cfg(),[]);assert.match(P.render(a),/Нет записей для сводной/);assert.equal(a.s.pivotCells.size,0);});
test('axis-free pivot returns exactly the whole filtered total',()=>{const a=app(cfg({rows:[],columns:[]}));const html=P.render(a);assert.equal((html.match(/data-pivot-row=/g)||[]).length,1);assert.equal(a.s.pivotCells.size,1);});
test('collapse action persists the view without changing records',()=>{const a=app();P.render(a);const path=a.s.pivotModel.rowRoot.children[0].path;assert(P.handleAction(a,'pivot-toggle-row',{path}));assert(a.saved&&a.rendered);assert(a.v.pivot.rowCollapsed.includes(path));assert.equal(t.rows.length,4);});
test('row and column axes swap without retaining invalid branch state',()=>{const a=app(cfg({rowCollapsed:['bad']}));assert(P.handleAction(a,'pivot-swap',{}));assert.equal(a.v.pivot.rows[0].key,'date');assert.equal(a.v.pivot.columns[0].key,'company');assert.equal(a.v.pivot.rowCollapsed.length,0);});
test('settings provide controls for both axes, measures and depth',()=>{const html=P.settings(app());for(const needle of ['Строки','Столбцы','Показатели','pivot-rule-key','pivot-measure-op','pivot-depth','pivot-swap'])assert(html.includes(needle));});
test('CSV contains all pages and guards spreadsheet formulas',()=>{const rows=Array.from({length:40},(_,i)=>({id:String(i),name:i===0?'=HYPERLINK("bad")':'name'+i,amount:i})),a=app(cfg({rows:rules('name'),columns:[],measures:[{id:'sum',key:'amount',op:'sum'}]}),rows);P.render(a);const csv=P.csv(a);assert.equal(csv.split('\r\n').length,42);assert(csv.includes("'=HYPERLINK"));assert(csv.includes('780'));});
test('too-wide pivot is explicitly blocked without partial matrix',()=>{const rows=Array.from({length:70},(_,i)=>({id:String(i),name:'name'+i,stage:'А',amount:i})),a=app(cfg({rows:rules('stage'),columns:rules('name'),measures:[{id:'n',op:'count'}],maxColumns:60}),rows),html=P.render(a);assert.match(html,/слишком широкая: 71/);assert(!html.includes('pivot-table'));assert.equal(a.s.pivotCells.size,0);assert.throws(()=>P.csv(a),/слишком широкая/);});
test('50000 records render only one page and totals include every record',()=>{const stress=context.IntegramStressSeed.baseline(),items=stress.tables.find(t=>t.id==='items'),c={rows:rules('name'),columns:[],measures:[{id:'count',op:'count'},{id:'qty',key:'qty',op:'sum'}]},a={...app(c),data:stress,t:items,rows:items.rows},started=Date.now(),html=P.render(a),elapsed=Date.now()-started;assert.equal(a.s.pivotModel.sourceCount,50000);assert.equal(a.s.pivotModel.getCell().summaries[0].value,50000);assert.equal((html.match(/data-pivot-row=/g)||[]).length,26);assert(a.s.pivotTotalRows>25);assert(elapsed<12000,'bounded render was too slow: '+elapsed);console.log('50000-row pivot ms',elapsed);});
test('excessive combinations stop explicitly without partial results',()=>{const rows=Array.from({length:100001},(_,i)=>({id:String(i),name:'unique-'+i})),a=app(cfg({rows:rules('name'),columns:[],measures:[{id:'count',op:'count'}]}),rows),html=P.render(a);assert.match(html,/Сократите число сочетаний/);assert.match(html,/Итоги не были усечены/);assert.equal(a.s.pivotCells.size,0);assert.equal(a.s.pivotModel,null);});
console.log('RESULT',passed+'/'+passed);
