const {fs,path,reportDir,chromium,server,start}=require('./harness.cjs'),assert=require('node:assert/strict');
const results=[];
(async()=>{const local=await start(),base=process.env.BASE_URL||local,browser=await chromium.launch({headless:true,channel:'chrome'});try{
for(const slug of ['contour']){
const ctx=await browser.newContext({viewport:{width:1440,height:1000},bypassCSP:true}),page=await ctx.newPage(),errors=[];page.setDefaultTimeout(16000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
await page.addInitScript(()=>{let Klass;Object.defineProperty(window,'IntegramApp',{configurable:true,get(){return Klass;},set(value){Klass=value;const render=value.prototype.render;value.prototype.render=function(...args){window.__pivotApps??={};window.__pivotApps[this.id]=this;return render.apply(this,args);};}});});
try{const url=new URL(base);url.searchParams.set('data','stress');url.hash=slug;await page.goto(url.href);const r=page.locator('#integram-'+slug),b=name=>r.getByRole('button',{name,exact:true});await r.locator('[data-action="screen"][data-screen="pivot"]').click();await r.locator('.pivot-table').waitFor();assert.match(await r.locator('.pivot-toolbar').innerText(),/12.?000/);
await r.locator('[data-action="panel"][data-panel="pivot"]').first().click();assert.equal(await r.locator('.settings-panel').count(),1);const panel=r.locator('.settings-panel');await panel.locator('[data-change="pivot-rule-key"][data-axis="rows"][data-index="0"]').selectOption('stage');await panel.locator('[data-action="pivot-rule-add"][data-axis="rows"]').click();await panel.locator('[data-change="pivot-rule-key"][data-axis="rows"][data-index="1"]').selectOption('company');await panel.locator('[data-change="pivot-rule-key"][data-axis="columns"][data-index="0"]').selectOption('date');await panel.locator('[data-change="pivot-rule-mode"][data-axis="columns"][data-index="0"]').selectOption('year');await panel.locator('[data-action="pivot-rule-add"][data-axis="columns"]').click();await panel.locator('[data-change="pivot-rule-key"][data-axis="columns"][data-index="1"]').selectOption('date');await panel.locator('[data-change="pivot-rule-mode"][data-axis="columns"][data-index="1"]').selectOption('quarter');await panel.locator('[data-action="panel-close"]').click();
const rowToggle=r.locator('[data-action="pivot-toggle-row"]').first(),rowPath=await rowToggle.getAttribute('data-path');await rowToggle.focus();await page.keyboard.press('Enter');assert.equal(await r.locator('[data-action="pivot-toggle-row"]').first().getAttribute('aria-expanded'),'false');const colToggle=r.locator('[data-action="pivot-toggle-column"]').first(),columnPath=await colToggle.getAttribute('data-path');await colToggle.focus();await page.keyboard.press('Space');assert.equal(await r.locator('[data-action="pivot-toggle-column"]').first().getAttribute('aria-expanded'),'false');
const before=await page.evaluate(slug=>{const a=__pivotApps[slug];return {sum:a.s.pivotModel.getCell().summaries.map(x=>x.text),config:JSON.stringify(a.v.pivot)};},slug);
await page.reload();await r.locator('.pivot-table').waitFor();assert.equal(await r.locator('[data-action="pivot-toggle-row"]').first().getAttribute('aria-expanded'),'false');assert.equal(await r.locator('[data-action="pivot-toggle-column"]').first().getAttribute('aria-expanded'),'false');assert.equal(await page.evaluate(slug=>JSON.stringify(__pivotApps[slug].v.pivot),slug),before.config);
const drillButton=r.locator('tbody [data-action="pivot-drill"]:not(:disabled)').first(),cellKey=await drillButton.getAttribute('data-cell'),expected=await page.evaluate(({slug,key})=>__pivotApps[slug].s.pivotCells.get(key),{slug,key:cellKey});await drillButton.click();await r.locator('[data-action="advanced-return"]').waitFor();const actual=await page.evaluate(slug=>__pivotApps[slug].rows.map(x=>String(x.id)),slug);assert.deepEqual(actual.slice().sort(),expected.slice().sort());await r.locator('[data-action="open"]').first().click();await r.locator('[data-action="back"]').click();await r.locator('[data-action="advanced-return"]').click();assert.equal(await page.evaluate(slug=>JSON.stringify(__pivotApps[slug].v.pivot),slug),before.config);
await r.locator('[data-action="panel"][data-panel="filters"]').click();await r.locator('[data-form="filter"] [name="key"]').selectOption('amount');await r.locator('[data-form="filter"] [name="op"]').selectOption('lt');await r.locator('[data-form="filter"] [name="value"]').fill('0');await b('Добавить условие').click();await r.locator('[data-action="panel-close"]').click();const expectedNegative=await page.evaluate(slug=>{const a=__pivotApps[slug];return a.t.rows.filter(x=>x.amount!==''&&x.amount<0).length;},slug);assert.equal(await page.evaluate(slug=>__pivotApps[slug].s.pivotModel.sourceCount,slug),expectedNegative);assert(expectedNegative>0);
const downloadEvent=page.waitForEvent('download');await r.locator('[data-action="pivot-export"]').click();const download=await downloadEvent,content=fs.readFileSync(await download.path(),'utf8');assert(content.startsWith('\uFEFF'));assert(content.includes('Общий итог'));assert(content.split('\r\n').length>50);
await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const visual=[];for(const theme of ['light','dark']){await page.locator('#preview-theme').selectOption(theme);for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,slug+' '+theme+' '+width);}const violations=await page.evaluate(async()=> (await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','best-practice']}})).violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)})));assert.deepEqual(violations,[]);visual.push({theme,axe:0});await page.screenshot({path:reportDir+'/pivot-'+slug+'-'+theme+'.png',fullPage:false});}
const headerGrid=await r.locator('.pivot-table').evaluate(table=>{const grid=[];for(let y=0;y<table.tHead.rows.length;y++){grid[y]??=[];let x=0;for(const cell of table.tHead.rows[y].cells){while(grid[y][x])x++;for(let yy=y;yy<y+cell.rowSpan;yy++){grid[yy]??=[];for(let xx=x;xx<x+cell.colSpan;xx++){if(grid[yy][xx])throw Error('Overlapping header cells');grid[yy][xx]=1;}}x+=cell.colSpan;}}const expected=table.tBodies[0].rows[0].cells.length;return {widths:grid.map(row=>row.length),expected};});assert(headerGrid.widths.every(n=>n===headerGrid.expected));assert.deepEqual(errors,[]);results.push({slug,pass:true,filteredRecords:expectedNegative,drillRecords:expected.length,rowPath,columnPath,visual,headers:headerGrid});console.log('PASS',slug,'pivot UX',JSON.stringify(results.at(-1)));
}catch(error){results.push({slug,pass:false,error:String(error),errors});console.log('FAIL',slug,String(error));await page.screenshot({path:reportDir+'/pivot-fail-'+slug+'.png',fullPage:false});}finally{await ctx.close();}
}
}finally{await browser.close();server.close();fs.writeFileSync(reportDir+'/pivot-browser-results.json',JSON.stringify(results,null,2));console.log('RESULT',results.filter(r=>r.pass).length+'/'+results.length);if(results.some(r=>!r.pass))process.exitCode=1;}})().catch(error=>{console.error(error);server.close();process.exitCode=1});
