const {fs,path,reportDir,chromium,server,start}=require('./harness.cjs');const assert=require('assert/strict');const results={axe:[],layout:[],performance:[],errors:[]};
(async()=>{const url=await start(),browser=await chromium.launch({headless:true,channel:'chrome'});try{for(const slug of ['contour','register','focus']){const context=await browser.newContext({viewport:{width:1440,height:1100},bypassCSP:true}),page=await context.newPage();page.on('pageerror',e=>results.errors.push({slug,error:e.message}));page.on('dialog',d=>d.accept());const r=page.locator('#integram-'+slug);const button=name=>r.getByRole('button',{name,exact:true});
for(const theme of ['light','dark']){await page.goto(url+'?qa='+theme+'#'+slug);await page.locator('#preview-theme').selectOption(theme);await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});
for(const screen of ['table','board','record','history','schema','filters','columns','sort','group','views','catalog']){
if(screen==='catalog')await button('Все таблицы').click();else if(screen==='table'){if(await button('Таблица').count())await button('Таблица').click();else await r.locator('[data-action="table"][data-table="deals"]').click();}else if(screen==='board')await button('Доска').click();else if(screen==='record')await r.locator('[data-action="open"]').first().click();else if(screen==='history')await button('История').click();else {if(await button('← К списку').count())await button('← К списку').click();if(await button('К записям').count())await button('К записям').click();if(await button('Закрыть настройки').count())await button('Закрыть настройки').click();if(screen==='schema')await button('Структура').click();else {await button('Таблица').click();await button({filters:'Фильтры',columns:'Столбцы',sort:'Сортировка',group:'Группы',views:'Сохранённые виды: Все записи'}[screen]).click();}}
const axe=await page.evaluate(async()=>{const result=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','best-practice']}});return result.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}));});results.axe.push({slug,theme,screen,violations:axe});if(axe.length)console.log('AXE',slug,theme,screen,JSON.stringify(axe).slice(0,1500));
for(const width of [320,390,768,1024,1440]){await page.setViewportSize({width,height:1100});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth);results.layout.push({slug,theme,screen,width,overflow});if(overflow>1)console.log('OVERFLOW',slug,theme,screen,width,overflow);}if(['table','board','record','schema'].includes(screen))await page.screenshot({path:`${reportDir}/${slug}-${screen}-${theme}.png`,fullPage:true});
}console.log('SCANNED',slug,theme);}
await context.close();}
// Measurements run without competing test contexts.
for(const slug of ['contour','register','focus']){const context=await browser.newContext({viewport:{width:1440,height:1100}}),page=await context.newPage();await page.goto(url+'#'+slug);await page.locator('#preview-data').selectOption('large');const r=page.locator('#integram-'+slug);await r.getByRole('button',{name:'Таблица',exact:true}).click();const before=await page.evaluate(()=>({nodes:document.querySelectorAll('*').length,rows:document.querySelectorAll('tr[data-row]').length,columns:document.querySelectorAll('thead th[data-key]').length,main:document.querySelectorAll('main').length,height:document.documentElement.scrollHeight}));const pin=await r.locator('tbody tr[data-row]').first().locator('td.pinned').boundingBox(),head=await r.locator('thead th.pinned').boundingBox();await r.locator('.table-wrap').evaluate(e=>{e.scrollLeft=800;e.scrollTop=300;});const pinAfter=await r.locator('tbody tr[data-row]').first().locator('td.pinned').boundingBox(),headAfter=await r.locator('thead th.pinned').boundingBox();const timings=[];for(let i=0;i<7;i++){await r.locator('[data-search]').fill('');const ms=await r.locator('[data-search]').evaluate(async el=>{const start=performance.now();el.value='Тестовая запись';el.dispatchEvent(new Event('input',{bubbles:true}));await new Promise(requestAnimationFrame);return performance.now()-start;});timings.push(ms);}await r.locator('[data-search]').fill('');await r.getByRole('button',{name:'Следующая страница',exact:true}).click();const next=await r.locator('tr[data-row]').first().getAttribute('data-row');const result={slug,...before,pinnedDeltaX:pinAfter.x-pin.x,headerDeltaY:headAfter.y-head.y,searchMedianMs:timings.sort((a,b)=>a-b)[3],searchTimingsMs:timings,nextPageFirst:next};results.performance.push(result);console.log('PERF',JSON.stringify(result));await context.close();}
}finally{fs.writeFileSync(reportDir+'/quality-results.json',JSON.stringify(results,null,2));await browser.close();server.close();console.log('SUMMARY',JSON.stringify({axeScans:results.axe.length,axeFailures:results.axe.filter(x=>x.violations.length).length,layouts:results.layout.length,overflow:results.layout.filter(x=>x.overflow>1).length,errors:results.errors.length}));if(results.axe.some(x=>x.violations.length)||results.layout.some(x=>x.overflow>1)||results.errors.length||results.performance.some(x=>x.rows>100||Math.abs(x.pinnedDeltaX)>1||Math.abs(x.headerDeltaY)>1))process.exitCode=1;}})().catch(e=>{console.error(e);process.exitCode=1;server.close()});
