const {fs,path,reportDir,chromium,server,start}=require('./harness.cjs');const assert=require('assert/strict');const results=[];
(async()=>{const local=await start(),base=process.env.BASE_URL||local,browser=await chromium.launch({headless:true,channel:'chrome'});try{
async function test(slug,name,fn){const ctx=await browser.newContext({viewport:{width:1440,height:1000},bypassCSP:true}),page=await ctx.newPage(),errors=[];page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());try{const url=new URL(base);url.searchParams.set('data','stress');url.hash=slug;await page.goto(url.href);const r=page.locator('#integram-'+slug),b=name=>r.getByRole('button',{name,exact:true});await r.locator('main').waitFor();if(slug==='focus')await b('Таблица').click();const detail=await fn({page,r,b,ctx});assert.deepEqual(errors,[]);results.push({slug,name,pass:true,...detail});console.log('PASS',slug,name,JSON.stringify(detail||{}));}catch(e){results.push({slug,name,pass:false,error:String(e),errors});console.log('FAIL',slug,name,String(e).slice(0,1000));await page.screenshot({path:reportDir+'/stress-fail-'+slug+'-'+name+'.png',fullPage:false});}finally{await ctx.close();}}
const count=async r=>r.locator('[data-result-count]').innerText();
async function search(page,r,value){await r.locator('[data-search]').fill(value);await page.waitForFunction(()=>!document.querySelector('.tools')?.hasAttribute('aria-busy'));}
for(const slug of ['contour','register','focus']){
await test(slug,'inventory-extremes',async({page,r,b})=>{
 const inventory=await page.evaluate(()=>IntegramStressSeed.baseline().tables.map(t=>({id:t.id,rows:t.rows.length,fields:t.fields.length})));assert.deepEqual(inventory.slice(0,3),[{id:'deals',rows:12000,fields:36},{id:'items',rows:50000,fields:18},{id:'payments',rows:25000,fields:22}]);assert.equal(inventory.reduce((sum,t)=>sum+t.rows,0),95782);
 const broken=await page.evaluate(()=>{const data=IntegramStressSeed.baseline(),ids=new Map(data.tables.map(t=>[t.id,new Set(t.rows.map(r=>String(r.id)))])),errors=[];for(const t of data.tables){if(ids.get(t.id).size!==t.rows.length)errors.push(t.id+' duplicates');for(const f of t.fields.filter(f=>f.type==='reference'))for(const row of t.rows)if(row[f.key]!==''&&row[f.key]!=null&&!ids.get(f.ref)?.has(String(row[f.key])))errors.push(t.id+':'+row.id+':'+f.key);}return errors;});assert.deepEqual(broken,[]);const compatible=await page.evaluate(slug=>{const d=IntegramStressSeed.baseline();return d.tables.every(t=>IntegramModel.shareCompatible(d,{version:3,table:t.id,view:IntegramModel.defaults(t,slug),schema:IntegramModel.schemaSignature(t)}));},slug);assert(compatible);const rejectsChangedSchema=await page.evaluate(()=>{const d=IntegramStressSeed.baseline(),t=d.tables[0],payload={version:3,table:t.id,view:IntegramModel.defaults(t,'contour'),schema:IntegramModel.schemaToken(t)};const changed={...t,fields:t.fields.map(f=>f.key==='amount'?{...f,label:'Другая сумма'}:f)};return !IntegramModel.shareCompatible({...d,tables:[changed,...d.tables.slice(1)]},payload);});assert(rejectsChangedSchema);
 assert.equal(await r.locator('tr[data-row]').count(),50);await r.locator('[name="quick-view"]').selectOption('0');assert.equal(await r.locator('thead th[data-key]').count(),36);assert.match(await r.locator('[data-row="700002"] td[data-key="amount"]').innerText(),/^0/);assert.match(await r.locator('[data-row="700003"] td[data-key="amount"]').innerText(),/Не указано/);assert.match(await r.locator('[data-row="700004"] td[data-key="amount"]').innerText(),/-12/);assert.match(await r.locator('[data-row="700005"] td[data-key="amount"]').innerText(),/0,01/);
 assert((await r.locator('[data-row="700001"]').boundingBox()).height<145);await r.locator('[data-row="700001"] td[data-key="note"] summary').click();assert((await r.locator('[data-row="700001"] td[data-key="note"] .long-value p').innerText()).length>2000);await r.locator('[data-row="700001"] td[data-key="note"] summary').click();assert.equal(await page.locator('img[src=x]').count(),0);
 await b('Все таблицы').click();assert.equal(await r.locator('.catalog-row').count(),9);return {inventory};
});
await test(slug,'50000-search-sort-export',async({page,r,b})=>{
 await r.locator('[data-action="table"][data-table="items"]').click();assert.match(await count(r),/50000 из 50000/);assert.equal(await r.locator('tr[data-row]').count(),50);let start=Date.now();await search(page,r,'SKU-0001499');const coldSearchMs=Date.now()-start;assert.match(await count(r),/33 из 50000/);assert(coldSearchMs<5000);await search(page,r,'SKU-0001498');await search(page,r,'');
 start=Date.now();await b('Сортировать: Наименование позиции / работы').click();const textSortMs=Date.now()-start;assert(textSortMs<5000);await b('Сортировать: Количество').click();const quantities=await r.locator('td[data-key="qty"] .cell-value span').allTextContents();assert(quantities.every(x=>x.trim()==='-1'));await b('Следующая страница').click();assert.equal(await r.locator('tr[data-row]').count(),50);await r.locator('[name="quick-view"]').selectOption('0');
 const pin=await r.locator('tbody td.pinned').first().boundingBox(),head=await r.locator('thead th.pinned').boundingBox();await r.locator('.table-wrap').evaluate(e=>{e.scrollLeft=1200;e.scrollTop=350;});const after=await r.locator('tbody td.pinned').first().boundingBox(),headAfter=await r.locator('thead th.pinned').boundingBox();assert.equal(after.x,pin.x);assert.equal(headAfter.y,head.y);
 const event=page.waitForEvent('download');start=Date.now();await b('Экспорт всей выборки в CSV').click();const download=await event,content=fs.readFileSync(await download.path(),'utf8');assert.equal(content.split('\r\n').length,50001);const exportMs=Date.now()-start;const nodes=await page.evaluate(()=>document.querySelectorAll('*').length);assert(nodes<13000);return {coldSearchMs,textSortMs,exportMs,exported:50000,domNodes:nodes};
});
await test(slug,'bounded-reference-filters',async({page,r,b})=>{
 await b('Фильтры').click();const f=r.locator('[data-form="filter"]');await f.locator('[name="key"]').selectOption('company');assert.equal(await f.locator('input[name="value"]').count(),80);await f.locator('[data-option-search]').fill('КА-00001');await f.locator('input[value="c0"]').check();await f.locator('[data-option-search]').fill('КА-00002');await f.locator('input[value="c1"]').check();await f.locator('[data-option-search]').fill('КА-01200');assert.equal(await f.locator('input[name="value"]').count(),1);await b('Добавить условие').click();const expected=await page.evaluate(()=>IntegramStressSeed.baseline().tables[0].rows.filter(r=>['c0','c1'].includes(r.company)).length);assert.match(await count(r),new RegExp('В выборке: '+expected+' из'));assert.equal(await r.locator('.filter-chip').count(),1);await b('Закрыть настройки').click();await r.locator('[data-action="open"]').first().click();await b('Следующая').click();assert(['c0','c1'].includes(await r.locator('[name="company"]').inputValue()));
 await r.locator('[data-action="table"][data-table="items"]').click();await b('Фильтры').click();await r.locator('[data-form="filter"] [name="key"]').selectOption('deal');assert.equal(await r.locator('input[name="value"]').count(),80);await r.locator('[data-option-search]').fill('#700001');await r.locator('input[value="700001"]').check();await b('Добавить условие').click();assert.match(await count(r),/В выборке: 5 из 50000/);return {matched:expected,maxOptions:80,referenceCatalog:12000};
});
await test(slug,'delta-save-undo-schema',async({page,r,b})=>{
 await r.locator('[data-action="table"][data-table="items"]').click();await r.locator('[data-action="open"]').first().click();await r.locator('[name="qty"]').fill('12.345');let start=Date.now();await b('Сохранить изменения').click();const saveMs=Date.now()-start;const stored=await page.evaluate(slug=>localStorage.getItem('integram-demo-v3-'+slug+'-stress-data'),slug);assert.equal(JSON.parse(stored).format,'integram-delta-v1');assert(stored.length<3000);await b('← К списку').click();await b('Отменить последнее изменение данных').click();await r.locator('[data-action="open"]').first().click();assert.equal(await r.locator('[name="qty"]').inputValue(),'0');await b('← К списку').click();await b('Повторить изменение данных').click();await r.locator('[data-action="open"]').first().click();assert.equal(await r.locator('[name="qty"]').inputValue(),'12.345');await b('← К списку').click();await b('Структура').click();await r.locator('[data-action="field-select"][data-key="batch"]').click();await b('Удалить поле').click();const patch=await page.evaluate(slug=>JSON.parse(localStorage.getItem('integram-demo-v3-'+slug+'-stress-data')),slug);assert.equal(patch.tables.items.upsert.length,1);assert(!patch.tables.items.metadata.fields.some(f=>f.key==='batch'));assert(JSON.stringify(patch).length<15000);await b('Отменить последнее изменение данных').click();await page.reload();await r.locator('[data-action="table"][data-table="items"]').click();await r.locator('[data-action="open"]').first().click();assert.equal(await r.locator('[name="qty"]').inputValue(),'12.345');assert.equal(await r.locator('[name="batch"]').count(),1);assert.equal(await page.evaluate(()=>IntegramStressSeed.baseline().tables.find(t=>t.id==='items').rows[0].qty),0);assert.equal(await r.locator('.storage-warning').count(),0);return {saveMs,storedCharacters:stored.length};
});
await test(slug,'views-share-empty',async({page,r,b})=>{
 await r.locator('[name="quick-view"]').selectOption({label:'Возвраты и корректировки'});const expected=await page.evaluate(()=>IntegramStressSeed.baseline().tables[0].rows.filter(r=>r.amount!==''&&r.amount<0).length);assert.match(await count(r),new RegExp(expected+' из 12000'));await r.locator('[data-action="panel"][data-panel="views"]').click();await b('Ссылка на этот вид').click();const link=await r.locator('[data-focus="share"]').inputValue();assert.equal(new URL(link).searchParams.get('data'),'stress');assert(link.length<7500);const other=await browser.newContext(),p=await other.newPage();try{await p.goto(link);assert.match(await p.locator('[data-result-count]').innerText(),new RegExp(expected+' из 12000'));}finally{await other.close();}
 await r.locator('[data-action="table"][data-table="claims"]').click();assert.match(await r.locator('.empty').innerText(),/Записей не найдено/);await b('Добавить запись').click();await r.locator('[name="name"]').fill('Проверка новой претензии');await b('Создать запись').click();await b('← К списку').click();assert.equal(await r.locator('tr[data-row]').count(),1);await b('Отменить последнее изменение данных').click();assert.equal(await r.locator('tr[data-row]').count(),0);return {sharedRows:expected};
});
await test(slug,'themes-widths-long-values',async({page,r,b})=>{
 await page.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const screens=[];for(const theme of ['light','dark']){await page.locator('#preview-theme').selectOption(theme);for(const table of ['deals','items','payments']){await r.locator('[data-action="table"][data-table="'+table+'"]').click();await r.locator('[name="quick-view"]').selectOption('0');for(const width of [320,390,768,1024,1440]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,table+':'+width);}
 const violations=await page.evaluate(async()=> (await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','best-practice']}})).violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)})));assert.deepEqual(violations,[]);screens.push({theme,table,axe:0});if(theme==='light')await page.screenshot({path:reportDir+'/stress-'+slug+'-'+table+'.png',fullPage:false});}}
 await r.locator('[data-action="table"][data-table="deals"]').click();await r.locator('[name="quick-view"]').selectOption('default');await b('Доска').click();await page.setViewportSize({width:390,height:844});await r.locator('[name="mobile-stage"]').selectOption('');assert.equal(await r.locator('.stage:visible').count(),1);assert.match(await r.locator('.stage:visible h3').innerText(),/Без этапа/);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:reportDir+'/stress-'+slug+'-mobile.png',fullPage:false});const mobile=await page.evaluate(async()=> (await axe.run(document)).violations.map(v=>v.id));assert.deepEqual(mobile,[]);return {screens,widthChecks:30,mobileAxe:0};
});
}
}finally{await browser.close();server.close();fs.writeFileSync(reportDir+'/stress-results.json',JSON.stringify(results,null,2));console.log('RESULT',results.filter(x=>x.pass).length+'/'+results.length);if(results.some(x=>!x.pass))process.exitCode=1;}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
